import {
  Order,
  Partner,
  Product,
  LivreurProfile,
  CloseuseProfile,
  PayoutRequest,
  ActivityItem,
  Conversation,
  AgencyAlert,
} from './types';

export const enoAgencies = [
  {
    id: 'cotonou',
    city: 'Cotonou',
    title: 'Agence Principale Littoral & Atlantique',
    coverage: 'Cotonou • Abomey-Calavi • Porto-Novo',
    primaryPhone: '+229 01 64 29 18 84',
    secondaryPhone: '+229 01 93 83 79 06',
    whatsapp: '2290164291884',
    address: 'Cadjehoun / Haie Vive, Cotonou, Bénin',
    status: 'Ouvert • 08h00 - 20h30',
    hubLead: 'Responsable Opérations Cotonou',
  },
  {
    id: 'lokossa',
    city: 'Lokossa',
    title: 'Agence Régionale Mono & Couffo',
    coverage: 'Lokossa • Mono • Couffo • Athiémé',
    primaryPhone: '+229 01 67 51 00 82',
    secondaryPhone: null,
    whatsapp: '2290167510082',
    address: 'Avenue Principale, Face Gare, Lokossa, Bénin',
    status: 'Ouvert • 08h00 - 19h00',
    hubLead: 'Responsable Antenne Lokossa',
  },
];

export const enoSocials = {
  tiktok: {
    handle: '@enolivraison',
    url: 'https://www.tiktok.com/@enolivraison',
    followers: '1 157+',
    likes: '4 351+',
    label: 'TikTok Officiel',
  },
  facebook: {
    name: 'Eno Livraison',
    url: 'https://www.facebook.com/enolivraison',
    label: 'Page Facebook',
  },
  instagram: {
    handle: '@enolivraison',
    url: 'https://www.instagram.com/enolivraison',
    label: 'Instagram',
  },
  whatsappCotonou: 'https://wa.me/2290164291884?text=Bonjour%20ENO%20LIVRAISON%2C%20je%20souhaite%20confier%20mes%20colis%20%C3%A0%20Cotonou',
  whatsappLokossa: 'https://wa.me/2290167510082?text=Bonjour%20ENO%20LIVRAISON%2C%20je%20souhaite%20confier%20mes%20colis%20%C3%A0%20Lokossa',
};

export const currentPartner: Partner = {
  id: 'p1',
  fullName: 'SINABEROGUI Jude',
  companyName: 'Afrimarket',
  email: 'judesinaberogui@gmail.com',
  phone: '+229 01 64 29 18 84',
  address: 'Cotonou, Bénin',
  city: 'Cotonou',
  isActive: true,
  isApproved: true,
  createdAt: '2026-01-15',
};

export const partners: Partner[] = [
  currentPartner,
  {
    id: 'p2',
    fullName: 'Epiphane Koumagnan',
    companyName: 'Bénin Shop',
    email: 'epiphane@beninshop.bj',
    phone: '+229 01 93 83 79 06',
    address: 'Zogbadjè, Abomey-Calavi',
    city: 'Abomey-Calavi',
    isActive: true,
    isApproved: true,
    createdAt: '2026-02-10',
  },
  {
    id: 'p3',
    fullName: 'Fatou Dossou',
    companyName: 'Dossou Fashion (Côte d\'Ivoire)',
    email: 'fatou@dossoufashion.ci',
    phone: '+225 07 89 45 12 30',
    address: 'Abidjan / Expédition Cotonou',
    city: 'Abidjan',
    isActive: true,
    isApproved: true,
    createdAt: '2026-03-05',
  },
  {
    id: 'p4',
    fullName: 'Arnaud Hounwanou',
    companyName: 'Lokossa Tech Store',
    email: 'arnaud@lokossatech.bj',
    phone: '+229 01 67 51 00 82',
    address: 'Centre-ville, Lokossa',
    city: 'Lokossa',
    isActive: true,
    isApproved: true,
    createdAt: '2026-03-12',
  },
];

export const livreurs: LivreurProfile[] = [
  {
    id: 'liv-1',
    name: 'Rachad ADECHINA',
    email: 'rachad.adechina@enolivraison.com',
    phone: '+229 01 97 45 12 00',
    zone: 'Cotonou Centre',
    secondaryZones: ['Akpakpa', 'Fidjrossè', 'Cadjehoun'],
    vehicle: 'Moto Yamaha YB-125',
    licensePlate: 'RB-4589-AF',
    isActive: true,
    availabilityStatus: 'IN_TRANSIT',
    mustChangePassword: false,
    assignedOrdersCount: 4,
    maxActiveCapacity: 8,
    deliveredTodayCount: 6,
    deliveredWeekCount: 38,
    deliveredMonthCount: 164,
    failedTodayCount: 0,
    cashCollectedToday: 78600,
    commissionPerDelivery: 1500,
    successRate: 97.4,
    avgDeliveryTimeMinutes: 34,
    lastActivityAt: 'Il y a 6 min',
  },
  {
    id: 'liv-2',
    name: 'Wilfried HOUNGBEDJI',
    email: 'wilfried.houngbedji@enolivraison.com',
    phone: '+229 01 66 32 98 11',
    zone: 'Abomey-Calavi',
    secondaryZones: ['Godomey', 'Arconville', 'Zogbadjè'],
    vehicle: 'Moto TVS HLX 150',
    licensePlate: 'RB-9102-BD',
    isActive: true,
    availabilityStatus: 'AVAILABLE',
    mustChangePassword: false,
    assignedOrdersCount: 2,
    maxActiveCapacity: 8,
    deliveredTodayCount: 5,
    deliveredWeekCount: 32,
    deliveredMonthCount: 142,
    failedTodayCount: 1,
    cashCollectedToday: 55200,
    commissionPerDelivery: 1500,
    successRate: 94.1,
    avgDeliveryTimeMinutes: 41,
    lastActivityAt: 'Il y a 12 min',
  },
  {
    id: 'liv-3',
    name: 'Rodrigue KOUTON',
    email: 'rodrigue.kouton@enolivraison.com',
    phone: '+229 01 95 14 78 22',
    zone: 'Porto-Novo',
    secondaryZones: ['Ouando', 'Sèmè-Kpodji', 'Djassin'],
    vehicle: 'Moto Bajaj Boxer 100',
    licensePlate: 'RB-2241-CC',
    isActive: true,
    availabilityStatus: 'PAUSED',
    mustChangePassword: false,
    assignedOrdersCount: 1,
    maxActiveCapacity: 8,
    deliveredTodayCount: 4,
    deliveredWeekCount: 26,
    deliveredMonthCount: 118,
    failedTodayCount: 0,
    cashCollectedToday: 42800,
    commissionPerDelivery: 1500,
    successRate: 96.0,
    avgDeliveryTimeMinutes: 38,
    lastActivityAt: 'Il y a 25 min',
  },
  {
    id: 'liv-4',
    name: 'Kevin ASSOGBA',
    email: 'kevin.assogba@enolivraison.com',
    phone: '+229 01 96 78 12 44',
    zone: 'Cotonou Nord',
    secondaryZones: ['Agla', 'Vedoko', 'Menontin'],
    vehicle: 'Moto Haojue 110',
    licensePlate: 'RB-7841-DD',
    isActive: true,
    availabilityStatus: 'AVAILABLE',
    mustChangePassword: false,
    assignedOrdersCount: 0,
    maxActiveCapacity: 8,
    deliveredTodayCount: 3,
    deliveredWeekCount: 29,
    deliveredMonthCount: 125,
    failedTodayCount: 0,
    cashCollectedToday: 36000,
    commissionPerDelivery: 1500,
    successRate: 98.2,
    avgDeliveryTimeMinutes: 29,
    lastActivityAt: 'Il y a 3 min',
  },
  {
    id: 'liv-5',
    name: 'David KOUASSI',
    email: 'david.kouassi@enolivraison.com',
    phone: '+229 01 67 44 99 01',
    zone: 'Abomey-Calavi',
    secondaryZones: ['Tankpe', 'Bidossessi'],
    vehicle: 'Moto Yamaha YB-125',
    licensePlate: 'RB-3301-EE',
    isActive: true,
    availabilityStatus: 'IN_TRANSIT',
    mustChangePassword: false,
    assignedOrdersCount: 3,
    maxActiveCapacity: 8,
    deliveredTodayCount: 4,
    deliveredWeekCount: 28,
    deliveredMonthCount: 110,
    failedTodayCount: 0,
    cashCollectedToday: 49500,
    commissionPerDelivery: 1500,
    successRate: 95.0,
    avgDeliveryTimeMinutes: 37,
    lastActivityAt: 'Il y a 8 min',
  },
  {
    id: 'liv-6',
    name: 'Moussa KANHOUN',
    email: 'moussa.kanhoun@gmail.com',
    phone: '+229 01 97 88 44 22',
    zone: 'Cotonou Littoral',
    secondaryZones: ['Cadjehoun', 'Haie Vive'],
    vehicle: 'Moto TVS 150',
    licensePlate: 'RB-1190-FF',
    isActive: true,
    availabilityStatus: 'OFFLINE',
    mustChangePassword: true,
    temporaryCode: '849201',
    assignedOrdersCount: 0,
    maxActiveCapacity: 8,
    deliveredTodayCount: 0,
    deliveredWeekCount: 12,
    deliveredMonthCount: 48,
    failedTodayCount: 0,
    cashCollectedToday: 0,
    commissionPerDelivery: 1500,
    successRate: 91.5,
    avgDeliveryTimeMinutes: 45,
    lastActivityAt: 'Hier à 19:30',
  },
];

export const closeuses: CloseuseProfile[] = [
  {
    id: 'cls-1',
    name: 'Inès TOVIHOUDJI',
    email: 'ines.tovihoudji@enolivraison.com',
    phone: '+229 01 64 29 18 84',
    isActive: true,
    mustChangePassword: false,
    callsTodayCount: 42,
    confirmedTodayCount: 37,
    conversionRate: 88,
  },
  {
    id: 'cls-2',
    name: 'Chimène AGBANGLA',
    email: 'chimene.agbangla@enolivraison.com',
    phone: '+229 01 93 83 79 06',
    isActive: true,
    mustChangePassword: false,
    callsTodayCount: 34,
    confirmedTodayCount: 29,
    conversionRate: 85,
  },
  {
    id: 'cls-3',
    name: 'Flora DOSSOU (Nouvelle)',
    email: 'flora.dossou@gmail.com',
    phone: '+229 01 61 77 99 33',
    isActive: true,
    mustChangePassword: true,
    temporaryCode: '315792',
    callsTodayCount: 0,
    confirmedTodayCount: 0,
    conversionRate: 0,
  },
];

export const initialPayoutRequests: PayoutRequest[] = [
  {
    id: 'pay-1',
    partnerId: 'p1',
    partnerName: 'Afrimarket',
    amount: 252400,
    operator: 'MTN',
    phone: '01 97 36 29 06',
    countryCode: '+229',
    requestedAt: '2026-09-03T10:30:00',
    status: 'PENDING',
  },
  {
    id: 'pay-3',
    partnerId: 'p3',
    partnerName: 'Dossou Fashion (Vendeur International)',
    amount: 360000,
    operator: 'USDT_TRC20',
    phone: '45 12 30 89',
    countryCode: '+222',
    cryptoAddress: 'TM1R9pQcKsXkQpXg8y6Jc5kZ3v4mN7bQ8L',
    cryptoNetwork: 'TRC-20 (Tron)',
    cryptoEstimatedUsdt: 600,
    requestedAt: '2026-09-03T11:15:00',
    status: 'PENDING',
  },
  {
    id: 'pay-2',
    partnerId: 'p2',
    partnerName: 'Bénin Shop',
    amount: 120000,
    operator: 'MOOV',
    phone: '01 93 83 79 06',
    countryCode: '+229',
    requestedAt: '2026-09-02T16:15:00',
    status: 'APPROVED',
    approvedAt: '2026-09-02T16:35:00',
    txReference: 'TX-ENO-984214',
  },
];

export const products: Product[] = [
  {
    id: 'prod1',
    name: 'ROULEAU DE COLORIAGE ET DESSIN MAGIQUE',
    price: 7800,
    initialStock: 150,
    remainingStock: 82,
    deliveredCount: 68,
    partnerId: 'p1',
    createdAt: '2026-01-20',
  },
  {
    id: 'prod2',
    name: 'MINI VENTILATEUR PORTATIF RECHARGEABLE USB',
    price: 9500,
    initialStock: 80,
    remainingStock: 34,
    deliveredCount: 46,
    partnerId: 'p1',
    createdAt: '2026-02-01',
  },
  {
    id: 'prod3',
    name: 'CORRECTEUR DE POSTURE DOS & ÉPAULES AJUSTABLE',
    price: 11000,
    initialStock: 60,
    remainingStock: 18,
    deliveredCount: 42,
    partnerId: 'p1',
    createdAt: '2026-02-15',
  },
  {
    id: 'prod4',
    name: 'MONTRE CONNECTÉE FITNESS PRO WATERPROOF',
    price: 18500,
    initialStock: 45,
    remainingStock: 12,
    deliveredCount: 33,
    partnerId: 'p2',
    createdAt: '2026-02-20',
  },
  {
    id: 'prod5',
    name: 'SERUM ANTI-TACHES ÉCLAT VISAGE 50ML',
    price: 14000,
    initialStock: 100,
    remainingStock: 48,
    deliveredCount: 52,
    partnerId: 'p3',
    createdAt: '2026-03-01',
  },
];

export const orders: Order[] = [
  {
    id: 'o1',
    orderNumber: 'CMD-BJ9K2L1A',
    clientName: 'SOULEYMANE DIOP',
    clientPhone: '+229 01 97 36 29 06',
    region: 'Littoral',
    address: 'AKPAKPA, Face Stade René Pleven',
    city: 'Cotonou',
    products: 'ROULEAU DE COLORIAGE (x2)',
    quantity: 2,
    totalPrice: 15600,
    deliveryFee: 2000,
    serviceFee: 800,
    status: 'EN_COURS',
    comment: 'Client confirmé par Inès. Livreur Rachad en route (créneau 14h-16h).',
    createdAt: '2026-09-03T09:15:00',
    updatedAt: '2026-09-03T11:00:00',
    partnerId: 'p1',
    partnerName: 'Afrimarket',
    assignedCloseuseId: 'cls-1',
    assignedCloseuseName: 'Inès T.',
    assignedLivreurId: 'liv-1',
    assignedLivreurName: 'Rachad A.',
    closingNotes: 'Client très réactif, prêt avec le montant exact.',
    callCount: 1,
    deliveryTimeSlot: '14h00 - 16h00',
  },
  {
    id: 'o2',
    orderNumber: 'CMD-BJH7X8P9',
    clientName: 'NADÈGE HOUNNOU',
    clientPhone: '+229 01 66 12 45 89',
    region: 'Atlantique',
    address: 'GODOMEY, Carrefour Togoudo',
    city: 'Abomey-Calavi',
    products: 'MINI VENTILATEUR RECHARGEABLE',
    quantity: 1,
    totalPrice: 9500,
    deliveryFee: 2000,
    serviceFee: 800,
    status: 'EN_ATTENTE',
    comment: 'Nouvelle commande boutique. À appeler en priorité.',
    createdAt: '2026-09-03T11:45:00',
    updatedAt: '2026-09-03T11:45:00',
    partnerId: 'p1',
    partnerName: 'Afrimarket',
    callCount: 0,
  },
  {
    id: 'o3',
    orderNumber: 'CMD-BJ3M4N5K',
    clientName: 'BRICE GBAGUIDI',
    clientPhone: '+229 01 95 88 77 44',
    region: 'Littoral',
    address: 'CADJEHOUN, Derrière Église St Michel',
    city: 'Cotonou',
    products: 'CORRECTEUR DE POSTURE',
    quantity: 1,
    totalPrice: 11000,
    deliveryFee: 2000,
    serviceFee: 800,
    status: 'CONFIRMEE',
    comment: 'Validé par Chimène. Prêt pour dispatch.',
    createdAt: '2026-09-03T08:30:00',
    updatedAt: '2026-09-03T10:15:00',
    partnerId: 'p1',
    partnerName: 'Afrimarket',
    assignedCloseuseId: 'cls-2',
    assignedCloseuseName: 'Chimène A.',
    assignedLivreurId: 'liv-1',
    assignedLivreurName: 'Rachad A.',
    closingNotes: 'Livraison bureau souhaitée avant 17h.',
    callCount: 1,
    deliveryTimeSlot: '15h30',
  },
  {
    id: 'o4',
    orderNumber: 'CMD-BJ2F4X7Y',
    clientName: 'MARIE-CLAIRE TOSSOU',
    clientPhone: '+229 01 67 89 23 45',
    region: 'Littoral',
    address: 'HAIE VIVE, Rue 12.045',
    city: 'Cotonou',
    products: 'ROULEAU DE COLORIAGE',
    quantity: 1,
    totalPrice: 7800,
    deliveryFee: 2000,
    serviceFee: 800,
    status: 'LIVREE',
    comment: 'Colis remis en main propre. Cash 7 800 F encaissé.',
    createdAt: '2026-09-02T14:00:00',
    updatedAt: '2026-09-02T16:30:00',
    deliveredAt: '2026-09-02T16:30:00',
    partnerId: 'p1',
    partnerName: 'Afrimarket',
    assignedCloseuseId: 'cls-1',
    assignedCloseuseName: 'Inès T.',
    assignedLivreurId: 'liv-1',
    assignedLivreurName: 'Rachad A.',
    codCollected: true,
  },
  {
    id: 'o5',
    orderNumber: 'CMD-BJ8R9T2W',
    clientName: 'JEAN-BAPTISTE DANSOU',
    clientPhone: '+229 01 96 44 33 22',
    region: 'Atlantique',
    address: 'TANKPÈ, Carrefour IITA',
    city: 'Abomey-Calavi',
    products: 'MINI VENTILATEUR RECHARGEABLE',
    quantity: 2,
    totalPrice: 19000,
    deliveryFee: 2000,
    serviceFee: 800,
    status: 'A_RAPPELER',
    comment: 'Injoignable 1er appel (occupé). Rappel programmé à 17h00.',
    createdAt: '2026-09-03T10:00:00',
    updatedAt: '2026-09-03T11:20:00',
    partnerId: 'p1',
    partnerName: 'Afrimarket',
    assignedCloseuseId: 'cls-1',
    assignedCloseuseName: 'Inès T.',
    closingNotes: 'Téléphone sonne mais ne décroche pas.',
    callCount: 1,
  },
  {
    id: 'o6',
    orderNumber: 'CMD-BJ5K9L2M',
    clientName: 'AÏCHA CISSE',
    clientPhone: '+229 01 68 00 11 22',
    region: 'Ouémé',
    address: 'OUANDO, Marché Ouando',
    city: 'Porto-Novo',
    products: 'SÉRUM ANTI-TACHES ÉCLAT',
    quantity: 1,
    totalPrice: 14000,
    deliveryFee: 2000,
    serviceFee: 800,
    status: 'EN_COURS',
    comment: 'Confirmé. Livreur Rodrigue en route.',
    createdAt: '2026-09-03T09:40:00',
    updatedAt: '2026-09-03T11:10:00',
    partnerId: 'p3',
    partnerName: 'Dossou Fashion (CI)',
    assignedCloseuseId: 'cls-2',
    assignedCloseuseName: 'Chimène A.',
    assignedLivreurId: 'liv-3',
    assignedLivreurName: 'Rodrigue K.',
    deliveryTimeSlot: '15h00',
  },
];

export function getPartnerById(partnerId: string): Partner | undefined {
  return partners.find((p) => p.id === partnerId);
}

export function getPartnerOrders(partnerId: string): Order[] {
  return orders.filter((o) => o.partnerId === partnerId);
}

export function getPartnerProducts(partnerId: string): Product[] {
  return products.filter((p) => p.partnerId === partnerId);
}

export function formatCFA(amount: number): string {
  return new Intl.NumberFormat('fr-FR').format(amount) + ' FCFA';
}

export function formatPrice(amount: number): string {
  return new Intl.NumberFormat('fr-FR').format(amount) + ' FCFA';
}

export function generateOrderNumber(): string {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  let result = 'CMD-BJ';
  for (let i = 0; i < 6; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return result;
}

// 🟢 Activité temps réel de l'agence (Agency Pulse)
export const initialAgencyPulseActivities: ActivityItem[] = [
  {
    id: 'act-1',
    type: 'ORDER_DELIVERED',
    title: 'Livraison réussie & COD encaissé',
    description: 'Rodrigue K. a remis le colis CMD-BJ5K9L2M (14 000 F) à Ouando.',
    time: 'Il y a 3 min',
    orderNumber: 'CMD-BJ5K9L2M',
    partnerName: 'Dossou Fashion',
    amount: 14000,
  },
  {
    id: 'act-2',
    type: 'ORDER_CONFIRMED',
    title: 'Commande confirmée par Closing',
    description: 'Inès T. a validé la commande CMD-BJ7X8Y9Z après 1 appel (15 min).',
    time: 'Il y a 11 min',
    orderNumber: 'CMD-BJ7X8Y9Z',
    partnerName: 'Afrimarket',
    amount: 23400,
  },
  {
    id: 'act-3',
    type: 'ORDER_DISPATCHED',
    title: 'Colis assigné au livreur de zone',
    description: 'CMD-BJ3C4D5E assignée à Gaston B. (Zone Akpakpa & PK10).',
    time: 'Il y a 18 min',
    orderNumber: 'CMD-BJ3C4D5E',
    partnerName: 'Bénin Shop',
    amount: 15600,
  },
  {
    id: 'act-4',
    type: 'PAYOUT_REQUESTED',
    title: 'Nouvelle demande de retrait soumise',
    description: 'Dossou Fashion demande 360 000 F CFA en USDT TRC-20.',
    time: 'Il y a 32 min',
    partnerName: 'Dossou Fashion',
    amount: 360000,
  },
  {
    id: 'act-5',
    type: 'MESSAGE_RECEIVED',
    title: 'Message urgent reçu au Support',
    description: 'Afrimarket : "Pouvez-vous prioriser la livraison à Haie Vive ?"',
    time: 'Il y a 45 min',
    partnerName: 'Afrimarket',
  },
];

// 💬 Conversations du Hub de Communication
export const initialConversations: Conversation[] = [
  {
    id: 'conv-1',
    partnerId: 'p1',
    partnerName: 'Jude Sina',
    companyName: 'Afrimarket',
    phone: '+229 01 97 36 29 06',
    lastMessage: 'Bonjour ! Quel est le délai moyen pour le virement MTN Money demandé ce matin ?',
    lastMessageAt: '11:42',
    unreadCount: 2,
    status: 'URGENT',
    priority: 'HIGH',
    assignedAgentName: 'Inès TOVIHOUDJI',
    assignedAgentRole: 'Superviseure Support',
    relatedOrderNumber: 'CMD-BJ7X8Y9Z',
    messages: [
      {
        id: 'm1',
        sender: 'PARTNER',
        senderName: 'Jude Sina (Afrimarket)',
        text: 'Bonjour le support ENO ! J\'ai 3 nouvelles commandes enregistrées sur Cotonou.',
        sentAt: '11:20',
      },
      {
        id: 'm2',
        sender: 'BOT',
        senderName: 'Assistant ENO',
        text: 'Bonjour Afrimarket ! Vos commandes ont été transmises à notre pôle closing. Nos opératrices appellent les clients sous 15 min.',
        sentAt: '11:21',
      },
      {
        id: 'm3',
        sender: 'PARTNER',
        senderName: 'Jude Sina (Afrimarket)',
        text: 'Parfait. Quel est le délai moyen pour le virement MTN Money demandé ce matin ?',
        sentAt: '11:42',
      },
    ],
  },
  {
    id: 'conv-2',
    partnerId: 'p3',
    partnerName: 'Marie Dossou',
    companyName: 'Dossou Fashion (Côte d\'Ivoire)',
    phone: '+225 07 45 12 30 89',
    lastMessage: 'J\'ai bien renseigné mon adresse USDT TRC-20 pour le reversement des fonds.',
    lastMessageAt: '10:15',
    unreadCount: 0,
    status: 'WAITING',
    priority: 'MEDIUM',
    assignedAgentName: 'Jude (PDG)',
    assignedAgentRole: 'Direction Générale',
    messages: [
      {
        id: 'm21',
        sender: 'PARTNER',
        senderName: 'Marie Dossou',
        text: 'Bonjour Monsieur, mes fonds de ventes à Cotonou sont prêts à être retirés en USDT.',
        sentAt: '10:10',
      },
      {
        id: 'm22',
        sender: 'PARTNER',
        senderName: 'Marie Dossou',
        text: 'J\'ai bien renseigné mon adresse USDT TRC-20 pour le reversement des fonds.',
        sentAt: '10:15',
      },
    ],
  },
  {
    id: 'conv-3',
    partnerId: 'p2',
    partnerName: 'Marius Houngbo',
    companyName: 'Bénin Shop Électro',
    phone: '+229 01 93 83 79 06',
    lastMessage: 'Merci pour la confirmation rapide du client de Calavi ! Super closing.',
    lastMessageAt: 'Hier',
    unreadCount: 0,
    status: 'RESOLVED',
    priority: 'LOW',
    assignedAgentName: 'Chimène A.',
    assignedAgentRole: 'Closeuse Senior',
    messages: [
      {
        id: 'm31',
        sender: 'PARTNER',
        senderName: 'Marius Houngbo',
        text: 'Merci pour la confirmation rapide du client de Calavi ! Super closing.',
        sentAt: 'Hier 16:30',
      },
    ],
  },
];

// ⚠️ Alertes Intelligentes du Centre d'Attention
export const initialAgencyAlerts: AgencyAlert[] = [
  {
    id: 'alt-1',
    severity: 'CRITICAL',
    title: '3 demandes de retrait nécessitent votre arbitrage',
    description: 'Montant cumulé : 612 400 F CFA en attente de déblocage (MTN Money & USDT TRC-20).',
    actionLabel: 'Arbitrer les retraits',
    actionHref: '/admin/finances',
    count: 3,
  },
  {
    id: 'alt-2',
    severity: 'WARNING',
    title: '1 client à rappeler en urgence',
    description: 'CMD-BJ9G0H1I (Afrimarket) — Injoignable au 1er appel, rappel programmé cet après-midi.',
    actionLabel: 'Voir la file closing',
    actionHref: '/admin/commandes',
    count: 1,
  },
  {
    id: 'alt-3',
    severity: 'INFO',
    title: 'Stock bas détecté : 1 produit sous le seuil critique',
    description: 'Pack Savon Noir & Curcuma (Bénin Shop) — Moins de 10 unités en entrepôt Cotonou.',
    actionLabel: 'Planifier ramassage',
    actionHref: '/admin/stocks',
    count: 1,
  },
];

