import { Order, Partner, Product, LivreurProfile, CloseuseProfile, PayoutRequest } from './types';

export const enoAgencies = [
  {
    id: 'cotonou',
    city: 'Cotonou',
    title: 'Agence Principale Littoral & Atlantique',
    coverage: 'Cotonou • Abomey-Calavi • Porto-Novo',
    primaryPhone: '+229 01 64 29 18 84',
    secondaryPhone: '+229 01 93 83 79 06',
    whatsapp: '2290164291884',
    address: 'Cadjehoun / Haie Vive, Cotonou, Bénin',
    status: 'Ouvert • 08h00 - 20h30',
    hubLead: 'Responsable Opérations Cotonou',
  },
  {
    id: 'lokossa',
    city: 'Lokossa',
    title: 'Agence Régionale Mono & Couffo',
    coverage: 'Lokossa • Mono • Couffo • Athiémé',
    primaryPhone: '+229 01 67 51 00 82',
    secondaryPhone: null,
    whatsapp: '2290167510082',
    address: 'Avenue Principale, Face Gare, Lokossa, Bénin',
    status: 'Ouvert • 08h00 - 19h00',
    hubLead: 'Responsable Antenne Lokossa',
  },
];

export const enoSocials = {
  tiktok: {
    handle: '@enolivraison',
    url: 'https://www.tiktok.com/@enolivraison',
    followers: '1 157+',
    likes: '4 351+',
    label: 'TikTok Officiel',
  },
  facebook: {
    name: 'Eno Livraison',
    url: 'https://www.facebook.com/enolivraison',
    label: 'Page Facebook',
  },
  instagram: {
    handle: '@enolivraison',
    url: 'https://www.instagram.com/enolivraison',
    label: 'Instagram',
  },
  whatsappCotonou: 'https://wa.me/2290164291884?text=Bonjour%20ENO%20LIVRAISON%2C%20je%20souhaite%20confier%20mes%20colis%20%C3%A0%20Cotonou',
  whatsappLokossa: 'https://wa.me/2290167510082?text=Bonjour%20ENO%20LIVRAISON%2C%20je%20souhaite%20confier%20mes%20colis%20%C3%A0%20Lokossa',
};

export const currentPartner: Partner = {
  id: 'p1',
  fullName: 'SINABEROGUI Jude',
  companyName: 'Afrimarket',
  email: 'judesinaberogui@gmail.com',
  phone: '+229 01 64 29 18 84',
  address: 'Cotonou, Bénin',
  city: 'Cotonou',
  isActive: true,
  isApproved: true,
  createdAt: '2026-01-15',
};

export const partners: Partner[] = [
  currentPartner,
  {
    id: 'p2',
    fullName: 'Epiphane Koumagnan',
    companyName: 'Bénin Shop',
    email: 'epiphane@beninshop.bj',
    phone: '+229 01 93 83 79 06',
    address: 'Zogbadjè, Abomey-Calavi',
    city: 'Abomey-Calavi',
    isActive: true,
    isApproved: true,
    createdAt: '2026-02-10',
  },
  {
    id: 'p3',
    fullName: 'Fatou Dossou',
    companyName: 'Dossou Fashion (Côte d\'Ivoire)',
    email: 'fatou@dossoufashion.ci',
    phone: '+225 07 89 45 12 30',
    address: 'Abidjan / Expédition Cotonou',
    city: 'Abidjan',
    isActive: true,
    isApproved: true,
    createdAt: '2026-03-05',
  },
  {
    id: 'p4',
    fullName: 'Arnaud Hounwanou',
    companyName: 'Lokossa Tech Store',
    email: 'arnaud@lokossatech.bj',
    phone: '+229 01 67 51 00 82',
    address: 'Centre-ville, Lokossa',
    city: 'Lokossa',
    isActive: true,
    isApproved: true,
    createdAt: '2026-03-12',
  },
];

export const livreurs: LivreurProfile[] = [
  {
    id: 'liv-1',
    name: 'Rachad ADECHINA',
    phone: '+229 01 97 45 12 00',
    zone: 'Cotonou Centre • Akpakpa • Fidjrossè',
    vehicle: 'Moto Yamaha YB-125',
    isActive: true,
    assignedOrdersCount: 6,
    deliveredTodayCount: 4,
    cashCollectedToday: 48600,
  },
  {
    id: 'liv-2',
    name: 'Wilfried HOUNGBEDJI',
    phone: '+229 01 66 32 98 11',
    zone: 'Abomey-Calavi • Godomey • Arconville',
    vehicle: 'Moto TVS HLX 150',
    isActive: true,
    assignedOrdersCount: 5,
    deliveredTodayCount: 3,
    cashCollectedToday: 35200,
  },
  {
    id: 'liv-3',
    name: 'Rodrigue KOUTON',
    phone: '+229 01 95 14 78 22',
    zone: 'Porto-Novo • Ouando • Sèmè-Kpodji',
    vehicle: 'Moto Bajaj Boxer 100',
    isActive: true,
    assignedOrdersCount: 3,
    deliveredTodayCount: 2,
    cashCollectedToday: 22800,
  },
];

export const closeuses: CloseuseProfile[] = [
  {
    id: 'cls-1',
    name: 'Inès TOVIHOUDJI',
    phone: '+229 01 64 29 18 84',
    isActive: true,
    callsTodayCount: 42,
    confirmedTodayCount: 37,
    conversionRate: 88,
  },
  {
    id: 'cls-2',
    name: 'Chimène AGBANGLA',
    phone: '+229 01 93 83 79 06',
    isActive: true,
    callsTodayCount: 34,
    confirmedTodayCount: 29,
    conversionRate: 85,
  },
];

export const initialPayoutRequests: PayoutRequest[] = [
  {
    id: 'pay-1',
    partnerId: 'p1',
    partnerName: 'Afrimarket',
    amount: 252400,
    operator: 'MTN',
    phone: '01 97 36 29 06',
    countryCode: '+229',
    requestedAt: '2026-09-03T10:30:00',
    status: 'PENDING',
  },
  {
    id: 'pay-3',
    partnerId: 'p3',
    partnerName: 'Dossou Fashion (Vendeur International)',
    amount: 360000,
    operator: 'USDT_TRC20',
    phone: '45 12 30 89',
    countryCode: '+222',
    cryptoAddress: 'TM1R9pQcKsXkQpXg8y6Jc5kZ3v4mN7bQ8L',
    cryptoNetwork: 'TRC-20 (Tron)',
    cryptoEstimatedUsdt: 600,
    requestedAt: '2026-09-03T11:15:00',
    status: 'PENDING',
  },
  {
    id: 'pay-2',
    partnerId: 'p2',
    partnerName: 'Bénin Shop',
    amount: 120000,
    operator: 'MOOV',
    phone: '01 93 83 79 06',
    countryCode: '+229',
    requestedAt: '2026-09-02T16:15:00',
    status: 'APPROVED',
    approvedAt: '2026-09-02T16:35:00',
    txReference: 'TX-ENO-984214',
  },
];

export const products: Product[] = [
  {
    id: 'prod1',
    name: 'ROULEAU DE COLORIAGE ET DESSIN MAGIQUE',
    price: 7800,
    initialStock: 150,
    remainingStock: 82,
    deliveredCount: 68,
    partnerId: 'p1',
    createdAt: '2026-01-20',
  },
  {
    id: 'prod2',
    name: 'MINI VENTILATEUR PORTATIF RECHARGEABLE USB',
    price: 9500,
    initialStock: 80,
    remainingStock: 34,
    deliveredCount: 46,
    partnerId: 'p1',
    createdAt: '2026-02-01',
  },
  {
    id: 'prod3',
    name: 'CORRECTEUR DE POSTURE DOS & ÉPAULES AJUSTABLE',
    price: 11000,
    initialStock: 60,
    remainingStock: 18,
    deliveredCount: 42,
    partnerId: 'p1',
    createdAt: '2026-02-15',
  },
  {
    id: 'prod4',
    name: 'MONTRE CONNECTÉE FITNESS PRO WATERPROOF',
    price: 18500,
    initialStock: 45,
    remainingStock: 12,
    deliveredCount: 33,
    partnerId: 'p2',
    createdAt: '2026-02-20',
  },
  {
    id: 'prod5',
    name: 'SERUM ANTI-TACHES ÉCLAT VISAGE 50ML',
    price: 14000,
    initialStock: 100,
    remainingStock: 48,
    deliveredCount: 52,
    partnerId: 'p3',
    createdAt: '2026-03-01',
  },
];

export const orders: Order[] = [
  {
    id: 'o1',
    orderNumber: 'CMD-BJ9K2L1A',
    clientName: 'SOULEYMANE DIOP',
    clientPhone: '+229 01 97 36 29 06',
    region: 'Littoral',
    address: 'AKPAKPA, Face Stade René Pleven',
    city: 'Cotonou',
    products: 'ROULEAU DE COLORIAGE (x2)',
    quantity: 2,
    totalPrice: 15600,
    deliveryFee: 2000,
    serviceFee: 800,
    status: 'EN_COURS',
    comment: 'Client confirmé par Inès. Livreur Rachad en route (créneau 14h-16h).',
    createdAt: '2026-09-03T09:15:00',
    updatedAt: '2026-09-03T11:00:00',
    partnerId: 'p1',
    partnerName: 'Afrimarket',
    assignedCloseuseId: 'cls-1',
    assignedCloseuseName: 'Inès T.',
    assignedLivreurId: 'liv-1',
    assignedLivreurName: 'Rachad A.',
    closingNotes: 'Client très réactif, prêt avec le montant exact.',
    callCount: 1,
    deliveryTimeSlot: '14h00 - 16h00',
  },
  {
    id: 'o2',
    orderNumber: 'CMD-BJH7X8P9',
    clientName: 'NADÈGE HOUNNOU',
    clientPhone: '+229 01 66 12 45 89',
    region: 'Atlantique',
    address: 'GODOMEY, Carrefour Togoudo',
    city: 'Abomey-Calavi',
    products: 'MINI VENTILATEUR RECHARGEABLE',
    quantity: 1,
    totalPrice: 9500,
    deliveryFee: 2000,
    serviceFee: 800,
    status: 'EN_ATTENTE',
    comment: 'Nouvelle commande boutique. À appeler en priorité.',
    createdAt: '2026-09-03T11:45:00',
    updatedAt: '2026-09-03T11:45:00',
    partnerId: 'p1',
    partnerName: 'Afrimarket',
    callCount: 0,
  },
  {
    id: 'o3',
    orderNumber: 'CMD-BJ3M4N5K',
    clientName: 'BRICE GBAGUIDI',
    clientPhone: '+229 01 95 88 77 44',
    region: 'Littoral',
    address: 'CADJEHOUN, Derrière Église St Michel',
    city: 'Cotonou',
    products: 'CORRECTEUR DE POSTURE',
    quantity: 1,
    totalPrice: 11000,
    deliveryFee: 2000,
    serviceFee: 800,
    status: 'CONFIRMEE',
    comment: 'Validé par Chimène. Prêt pour dispatch.',
    createdAt: '2026-09-03T08:30:00',
    updatedAt: '2026-09-03T10:15:00',
    partnerId: 'p1',
    partnerName: 'Afrimarket',
    assignedCloseuseId: 'cls-2',
    assignedCloseuseName: 'Chimène A.',
    assignedLivreurId: 'liv-1',
    assignedLivreurName: 'Rachad A.',
    closingNotes: 'Livraison bureau souhaitée avant 17h.',
    callCount: 1,
    deliveryTimeSlot: '15h30',
  },
  {
    id: 'o4',
    orderNumber: 'CMD-BJ2F4X7Y',
    clientName: 'MARIE-CLAIRE TOSSOU',
    clientPhone: '+229 01 67 89 23 45',
    region: 'Littoral',
    address: 'HAIE VIVE, Rue 12.045',
    city: 'Cotonou',
    products: 'ROULEAU DE COLORIAGE',
    quantity: 1,
    totalPrice: 7800,
    deliveryFee: 2000,
    serviceFee: 800,
    status: 'LIVREE',
    comment: 'Colis remis en main propre. Cash 7 800 F encaissé.',
    createdAt: '2026-09-02T14:00:00',
    updatedAt: '2026-09-02T16:30:00',
    deliveredAt: '2026-09-02T16:30:00',
    partnerId: 'p1',
    partnerName: 'Afrimarket',
    assignedCloseuseId: 'cls-1',
    assignedCloseuseName: 'Inès T.',
    assignedLivreurId: 'liv-1',
    assignedLivreurName: 'Rachad A.',
    codCollected: true,
  },
  {
    id: 'o5',
    orderNumber: 'CMD-BJ8R9T2W',
    clientName: 'JEAN-BAPTISTE DANSOU',
    clientPhone: '+229 01 96 44 33 22',
    region: 'Atlantique',
    address: 'TANKPÈ, Carrefour IITA',
    city: 'Abomey-Calavi',
    products: 'MINI VENTILATEUR RECHARGEABLE',
    quantity: 2,
    totalPrice: 19000,
    deliveryFee: 2000,
    serviceFee: 800,
    status: 'A_RAPPELER',
    comment: 'Injoignable 1er appel (occupé). Rappel programmé à 17h00.',
    createdAt: '2026-09-03T10:00:00',
    updatedAt: '2026-09-03T11:20:00',
    partnerId: 'p1',
    partnerName: 'Afrimarket',
    assignedCloseuseId: 'cls-1',
    assignedCloseuseName: 'Inès T.',
    closingNotes: 'Téléphone sonne mais ne décroche pas.',
    callCount: 1,
  },
  {
    id: 'o6',
    orderNumber: 'CMD-BJ5K9L2M',
    clientName: 'AÏCHA CISSE',
    clientPhone: '+229 01 68 00 11 22',
    region: 'Ouémé',
    address: 'OUANDO, Marché Ouando',
    city: 'Porto-Novo',
    products: 'SÉRUM ANTI-TACHES ÉCLAT',
    quantity: 1,
    totalPrice: 14000,
    deliveryFee: 2000,
    serviceFee: 800,
    status: 'EN_COURS',
    comment: 'Confirmé. Livreur Rodrigue en route.',
    createdAt: '2026-09-03T09:40:00',
    updatedAt: '2026-09-03T11:10:00',
    partnerId: 'p3',
    partnerName: 'Dossou Fashion (CI)',
    assignedCloseuseId: 'cls-2',
    assignedCloseuseName: 'Chimène A.',
    assignedLivreurId: 'liv-3',
    assignedLivreurName: 'Rodrigue K.',
    deliveryTimeSlot: '15h00',
  },
];

export function getPartnerById(partnerId: string): Partner | undefined {
  return partners.find((p) => p.id === partnerId);
}

export function getPartnerOrders(partnerId: string): Order[] {
  return orders.filter((o) => o.partnerId === partnerId);
}

export function getPartnerProducts(partnerId: string): Product[] {
  return products.filter((p) => p.partnerId === partnerId);
}

export function formatCFA(amount: number): string {
  return new Intl.NumberFormat('fr-FR').format(amount) + ' F CFA';
}

export function formatPrice(amount: number): string {
  return new Intl.NumberFormat('fr-FR').format(amount) + ' F';
}

export function generateOrderNumber(): string {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  let result = 'CMD-BJ';
  for (let i = 0; i < 6; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return result;
}
