import {
  Order,
  Partner,
  Product,
  LivreurProfile,
  CloseuseProfile,
  PayoutRequest,
  ActivityItem,
  Conversation,
  AgencyAlert,
  FinancialTransaction,
  CodCollection,
  CodRemittance,
  FinancialAuditLog,
} from './types';

export const enoAgencies = [
  {
    id: 'cotonou',
    city: 'Cotonou',
    title: 'Agence Principale Littoral & Atlantique',
    coverage: 'Cotonou • Abomey-Calavi • Porto-Novo',
    primaryPhone: '+229 01 64 29 18 84',
    secondaryPhone: '+229 01 93 83 79 06',
    whatsapp: '2290164291884',
    address: 'Cadjehoun / Haie Vive, Cotonou, Bénin',
    status: 'Ouvert • 08h00 - 20h30',
    hubLead: 'Responsable Opérations Cotonou',
  },
  {
    id: 'lokossa',
    city: 'Lokossa',
    title: 'Agence Régionale Mono & Couffo',
    coverage: 'Lokossa • Mono • Couffo • Athiémé',
    primaryPhone: '+229 01 67 51 00 82',
    secondaryPhone: null,
    whatsapp: '2290167510082',
    address: 'Avenue Principale, Face Gare, Lokossa, Bénin',
    status: 'Ouvert • 08h00 - 19h00',
    hubLead: 'Responsable Antenne Lokossa',
  },
];

export const enoSocials = {
  tiktok: {
    handle: '@enolivraison',
    url: 'https://www.tiktok.com/@enolivraison',
    followers: '1 157+',
    likes: '4 351+',
    label: 'TikTok Officiel',
  },
  facebook: {
    name: 'Eno Livraison',
    url: 'https://www.facebook.com/enolivraison',
    label: 'Page Facebook',
  },
  instagram: {
    handle: '@enolivraison',
    url: 'https://www.instagram.com/enolivraison',
    label: 'Instagram',
  },
  whatsappCotonou: 'https://wa.me/2290164291884?text=Bonjour%20ENO%20LIVRAISON%2C%20je%20souhaite%20confier%20mes%20colis%20%C3%A0%20Cotonou',
  whatsappLokossa: 'https://wa.me/2290167510082?text=Bonjour%20ENO%20LIVRAISON%2C%20je%20souhaite%20confier%20mes%20colis%20%C3%A0%20Lokossa',
};

export const currentPartner: Partner = {
  id: 'p1',
  fullName: 'SINABEROGUI Jude',
  companyName: 'Afrimarket',
  email: 'judesinaberogui@gmail.com',
  phone: '+229 01 64 29 18 84',
  address: 'Cadjehoun, Cotonou, Bénin',
  city: 'Cotonou',
  isActive: true,
  isApproved: true,
  status: 'ACTIVE',
  category: 'Cosmétique & Beauté',
  websiteUrl: 'https://afrimarket.bj',
  deliveryFeeDefault: 2000,
  agencyCommissionDefault: 800,
  onboardingStep: 6,
  availableBalance: 4820000,
  pendingBalance: 1250000,
  ordersCountToday: 24,
  ordersCountMonth: 412,
  gmvProcessed: 18450000,
  confirmationRate: 88.5,
  deliverySuccessRate: 94.2,
  lastPayoutDate: '18 août 2026',
  lastActivityAt: 'Il y a 4 min',
  createdAt: '2026-01-15',
};

export const partners: Partner[] = [
  currentPartner,
  {
    id: 'p2',
    fullName: 'Epiphane Koumagnan',
    companyName: 'Bénin Shop',
    email: 'epiphane@beninshop.bj',
    phone: '+229 01 93 83 79 06',
    address: 'Zogbadjè, Abomey-Calavi',
    city: 'Abomey-Calavi',
    isActive: true,
    isApproved: true,
    status: 'ACTIVE',
    category: 'Électronique & High-Tech',
    websiteUrl: 'https://beninshop.bj',
    deliveryFeeDefault: 2000,
    agencyCommissionDefault: 800,
    onboardingStep: 6,
    availableBalance: 2450000,
    pendingBalance: 680000,
    ordersCountToday: 18,
    ordersCountMonth: 320,
    gmvProcessed: 12800000,
    confirmationRate: 84.0,
    deliverySuccessRate: 91.0,
    lastPayoutDate: '22 août 2026',
    lastActivityAt: 'Il y a 12 min',
    createdAt: '2026-02-10',
  },
  {
    id: 'p3',
    fullName: 'Fatou Dossou',
    companyName: 'Dossou Fashion (Côte d\'Ivoire)',
    email: 'fatou@dossoufashion.ci',
    phone: '+225 07 89 45 12 30',
    address: 'Abidjan / Hub Cotonou',
    city: 'Abidjan',
    isActive: true,
    isApproved: true,
    status: 'ACTIVE',
    category: 'Mode & Prêt-à-porter',
    websiteUrl: 'https://dossoufashion.com',
    deliveryFeeDefault: 2500,
    agencyCommissionDefault: 1000,
    onboardingStep: 6,
    availableBalance: 3600000,
    pendingBalance: 950000,
    ordersCountToday: 14,
    ordersCountMonth: 275,
    gmvProcessed: 14200000,
    confirmationRate: 86.2,
    deliverySuccessRate: 93.4,
    lastPayoutDate: '15 août 2026',
    lastActivityAt: 'Il y a 25 min',
    createdAt: '2026-03-05',
  },
  {
    id: 'p4',
    fullName: 'Arnaud Hounwanou',
    companyName: 'Lokossa Tech Store',
    email: 'arnaud@lokossatech.bj',
    phone: '+229 01 67 51 00 82',
    address: 'Centre-ville, Lokossa',
    city: 'Lokossa',
    isActive: true,
    isApproved: true,
    status: 'ACTIVE',
    category: 'Smartphones & Gadgets',
    websiteUrl: 'https://lokossatech.bj',
    deliveryFeeDefault: 2000,
    agencyCommissionDefault: 800,
    onboardingStep: 6,
    availableBalance: 1120000,
    pendingBalance: 310000,
    ordersCountToday: 8,
    ordersCountMonth: 140,
    gmvProcessed: 5600000,
    confirmationRate: 81.5,
    deliverySuccessRate: 89.0,
    lastPayoutDate: '28 août 2026',
    lastActivityAt: 'Il y a 1 heure',
    createdAt: '2026-03-12',
  },
  {
    id: 'p5',
    fullName: 'Karelle Hounsou',
    companyName: 'K-Beauty Cotonou',
    email: 'karelle@kbeauty.bj',
    phone: '+229 01 97 11 22 33',
    address: 'Fidjrossè Calvaire',
    city: 'Cotonou',
    isActive: true,
    isApproved: false,
    status: 'ONBOARDING',
    category: 'Skincare Coréen',
    websiteUrl: 'https://kbeauty.bj',
    deliveryFeeDefault: 2000,
    agencyCommissionDefault: 800,
    onboardingStep: 3,
    availableBalance: 0,
    pendingBalance: 0,
    ordersCountToday: 0,
    ordersCountMonth: 0,
    gmvProcessed: 0,
    confirmationRate: 0,
    deliverySuccessRate: 0,
    lastPayoutDate: 'Nouveau',
    lastActivityAt: 'Hier à 16:30',
    createdAt: '2026-08-30',
  },
  {
    id: 'p6',
    fullName: 'Gildas Tossou',
    companyName: 'Royal Shoes BJ',
    email: 'gildas@royalshoes.bj',
    phone: '+229 01 62 44 88 00',
    address: 'Haie Vive, Cotonou',
    city: 'Cotonou',
    isActive: true,
    isApproved: false,
    status: 'PENDING_VERIFICATION',
    category: 'Chaussures & Maroquinerie',
    websiteUrl: 'https://royalshoes.bj',
    deliveryFeeDefault: 2000,
    agencyCommissionDefault: 800,
    onboardingStep: 4,
    availableBalance: 450000,
    pendingBalance: 180000,
    ordersCountToday: 2,
    ordersCountMonth: 15,
    gmvProcessed: 850000,
    confirmationRate: 75.0,
    deliverySuccessRate: 80.0,
    lastPayoutDate: 'Aucun',
    lastActivityAt: 'Il y a 3 heures',
    createdAt: '2026-08-22',
  },
  {
    id: 'p7',
    fullName: 'Blandine Agbo',
    companyName: 'Afro Hair Care',
    email: 'blandine@afrohair.bj',
    phone: '+229 01 95 33 22 11',
    address: 'Akpakpa Dodomè',
    city: 'Cotonou',
    isActive: false,
    isApproved: true,
    status: 'SUSPENDED',
    suspensionReason: 'Taux de retour anormalement élevé (>40%) et contestation répétée des livraisons.',
    category: 'Soins Capillaires',
    websiteUrl: 'https://afrohair.bj',
    deliveryFeeDefault: 2000,
    agencyCommissionDefault: 800,
    onboardingStep: 6,
    availableBalance: 210000,
    pendingBalance: 0,
    ordersCountToday: 0,
    ordersCountMonth: 45,
    gmvProcessed: 1950000,
    confirmationRate: 62.0,
    deliverySuccessRate: 58.5,
    lastPayoutDate: '02 août 2026',
    lastActivityAt: 'Suspendu le 24 août',
    createdAt: '2026-04-10',
  },
];

export const livreurs: LivreurProfile[] = [
  {
    id: 'liv-1',
    name: 'Rachad ADECHINA',
    email: 'rachad.adechina@enolivraison.com',
    phone: '+229 01 97 45 12 00',
    zone: 'Cotonou Centre',
    secondaryZones: ['Akpakpa', 'Fidjrossè', 'Cadjehoun'],
    vehicle: 'Moto Yamaha YB-125',
    licensePlate: 'RB-4589-AF',
    isActive: true,
    availabilityStatus: 'IN_TRANSIT',
    mustChangePassword: false,
    assignedOrdersCount: 4,
    maxActiveCapacity: 8,
    deliveredTodayCount: 6,
    deliveredWeekCount: 38,
    deliveredMonthCount: 164,
    failedTodayCount: 0,
    cashCollectedToday: 78600,
    commissionPerDelivery: 1500,
    successRate: 97.4,
    avgDeliveryTimeMinutes: 34,
    lastActivityAt: 'Il y a 6 min',
  },
  {
    id: 'liv-2',
    name: 'Wilfried HOUNGBEDJI',
    email: 'wilfried.houngbedji@enolivraison.com',
    phone: '+229 01 66 32 98 11',
    zone: 'Abomey-Calavi',
    secondaryZones: ['Godomey', 'Arconville', 'Zogbadjè'],
    vehicle: 'Moto TVS HLX 150',
    licensePlate: 'RB-9102-BD',
    isActive: true,
    availabilityStatus: 'AVAILABLE',
    mustChangePassword: false,
    assignedOrdersCount: 2,
    maxActiveCapacity: 8,
    deliveredTodayCount: 5,
    deliveredWeekCount: 32,
    deliveredMonthCount: 142,
    failedTodayCount: 1,
    cashCollectedToday: 55200,
    commissionPerDelivery: 1500,
    successRate: 94.1,
    avgDeliveryTimeMinutes: 41,
    lastActivityAt: 'Il y a 12 min',
  },
  {
    id: 'liv-3',
    name: 'Rodrigue KOUTON',
    email: 'rodrigue.kouton@enolivraison.com',
    phone: '+229 01 95 14 78 22',
    zone: 'Porto-Novo',
    secondaryZones: ['Ouando', 'Sèmè-Kpodji', 'Djassin'],
    vehicle: 'Moto Bajaj Boxer 100',
    licensePlate: 'RB-2241-CC',
    isActive: true,
    availabilityStatus: 'PAUSED',
    mustChangePassword: false,
    assignedOrdersCount: 1,
    maxActiveCapacity: 8,
    deliveredTodayCount: 4,
    deliveredWeekCount: 26,
    deliveredMonthCount: 118,
    failedTodayCount: 0,
    cashCollectedToday: 42800,
    commissionPerDelivery: 1500,
    successRate: 96.0,
    avgDeliveryTimeMinutes: 38,
    lastActivityAt: 'Il y a 25 min',
  },
  {
    id: 'liv-4',
    name: 'Kevin ASSOGBA',
    email: 'kevin.assogba@enolivraison.com',
    phone: '+229 01 96 78 12 44',
    zone: 'Cotonou Nord',
    secondaryZones: ['Agla', 'Vedoko', 'Menontin'],
    vehicle: 'Moto Haojue 110',
    licensePlate: 'RB-7841-DD',
    isActive: true,
    availabilityStatus: 'AVAILABLE',
    mustChangePassword: false,
    assignedOrdersCount: 0,
    maxActiveCapacity: 8,
    deliveredTodayCount: 3,
    deliveredWeekCount: 29,
    deliveredMonthCount: 125,
    failedTodayCount: 0,
    cashCollectedToday: 36000,
    commissionPerDelivery: 1500,
    successRate: 98.2,
    avgDeliveryTimeMinutes: 29,
    lastActivityAt: 'Il y a 3 min',
  },
  {
    id: 'liv-5',
    name: 'David KOUASSI',
    email: 'david.kouassi@enolivraison.com',
    phone: '+229 01 67 44 99 01',
    zone: 'Abomey-Calavi',
    secondaryZones: ['Tankpe', 'Bidossessi'],
    vehicle: 'Moto Yamaha YB-125',
    licensePlate: 'RB-3301-EE',
    isActive: true,
    availabilityStatus: 'IN_TRANSIT',
    mustChangePassword: false,
    assignedOrdersCount: 3,
    maxActiveCapacity: 8,
    deliveredTodayCount: 4,
    deliveredWeekCount: 28,
    deliveredMonthCount: 110,
    failedTodayCount: 0,
    cashCollectedToday: 49500,
    commissionPerDelivery: 1500,
    successRate: 95.0,
    avgDeliveryTimeMinutes: 37,
    lastActivityAt: 'Il y a 8 min',
  },
  {
    id: 'liv-6',
    name: 'Moussa KANHOUN',
    email: 'moussa.kanhoun@gmail.com',
    phone: '+229 01 97 88 44 22',
    zone: 'Cotonou Littoral',
    secondaryZones: ['Cadjehoun', 'Haie Vive'],
    vehicle: 'Moto TVS 150',
    licensePlate: 'RB-1190-FF',
    isActive: true,
    availabilityStatus: 'OFFLINE',
    mustChangePassword: true,
    temporaryCode: '849201',
    assignedOrdersCount: 0,
    maxActiveCapacity: 8,
    deliveredTodayCount: 0,
    deliveredWeekCount: 12,
    deliveredMonthCount: 48,
    failedTodayCount: 0,
    cashCollectedToday: 0,
    commissionPerDelivery: 1500,
    successRate: 91.5,
    avgDeliveryTimeMinutes: 45,
    lastActivityAt: 'Hier à 19:30',
  },
];

export const closeuses: CloseuseProfile[] = [
  {
    id: 'cls-1',
    name: 'Sarah ADANHO',
    email: 'sarah.adanho@enolivraison.com',
    phone: '+229 01 64 29 18 84',
    isActive: true,
    availabilityStatus: 'AVAILABLE',
    mustChangePassword: false,
    callsTodayCount: 42,
    confirmedTodayCount: 34,
    confirmedWeekCount: 198,
    confirmedMonthCount: 840,
    cancelledTodayCount: 3,
    unreachableTodayCount: 5,
    callbacksScheduledToday: 4,
    conversionRate: 82.5,
    maxActiveOrders: 15,
    maxActiveConversations: 5,
    activeOrdersCount: 4,
    activeConversationsCount: 2,
    commissionPerConfirmation: 750,
    avgProcessingTimeMinutes: 4.2,
    languages: ['Français', 'Fon', 'Yoruba'],
    zones: ['Cotonou', 'Calavi'],
    skills: ['High-Ticket', 'Cosmétique', 'B2B'],
    lastActivityAt: 'Il y a 2 min',
  },
  {
    id: 'cls-2',
    name: 'Marie KOUASSI',
    email: 'marie.kouassi@enolivraison.com',
    phone: '+229 01 93 83 79 06',
    isActive: true,
    availabilityStatus: 'BUSY',
    mustChangePassword: false,
    callsTodayCount: 38,
    confirmedTodayCount: 29,
    confirmedWeekCount: 176,
    confirmedMonthCount: 790,
    cancelledTodayCount: 4,
    unreachableTodayCount: 5,
    callbacksScheduledToday: 6,
    conversionRate: 78.4,
    maxActiveOrders: 15,
    maxActiveConversations: 5,
    activeOrdersCount: 11,
    activeConversationsCount: 4,
    commissionPerConfirmation: 750,
    avgProcessingTimeMinutes: 5.1,
    languages: ['Français', 'Fon'],
    zones: ['Cotonou Littoral', 'Porto-Novo'],
    skills: ['Mode & Textile', 'Électronique'],
    lastActivityAt: 'Il y a 5 min',
  },
  {
    id: 'cls-3',
    name: 'Carine DOSSOU',
    email: 'carine.dossou@enolivraison.com',
    phone: '+229 01 61 77 99 33',
    isActive: true,
    availabilityStatus: 'PAUSED',
    mustChangePassword: false,
    callsTodayCount: 28,
    confirmedTodayCount: 22,
    confirmedWeekCount: 145,
    confirmedMonthCount: 650,
    cancelledTodayCount: 2,
    unreachableTodayCount: 4,
    callbacksScheduledToday: 3,
    conversionRate: 81.0,
    maxActiveOrders: 15,
    maxActiveConversations: 5,
    activeOrdersCount: 6,
    activeConversationsCount: 1,
    commissionPerConfirmation: 750,
    avgProcessingTimeMinutes: 4.8,
    languages: ['Français', 'Goun', 'Yoruba'],
    zones: ['Porto-Novo', 'Sèmè-Kpodji'],
    skills: ['Gadgets Tech', 'Maison'],
    lastActivityAt: 'Il y a 18 min',
  },
  {
    id: 'cls-4',
    name: 'Inès TOVIHOUDJI',
    email: 'ines.tovihoudji@enolivraison.com',
    phone: '+229 01 97 55 22 11',
    isActive: true,
    availabilityStatus: 'AVAILABLE',
    mustChangePassword: false,
    callsTodayCount: 31,
    confirmedTodayCount: 26,
    confirmedWeekCount: 160,
    confirmedMonthCount: 710,
    cancelledTodayCount: 2,
    unreachableTodayCount: 3,
    callbacksScheduledToday: 2,
    conversionRate: 83.8,
    maxActiveOrders: 15,
    maxActiveConversations: 5,
    activeOrdersCount: 3,
    activeConversationsCount: 1,
    commissionPerConfirmation: 750,
    avgProcessingTimeMinutes: 3.9,
    languages: ['Français', 'Fon', 'Anglais'],
    zones: ['Cotonou Centre'],
    skills: ['Vente Express', 'Relations VIP'],
    lastActivityAt: 'Il y a 8 min',
  },
  {
    id: 'cls-5',
    name: 'Flora AGBANGLA',
    email: 'flora.agbangla@gmail.com',
    phone: '+229 01 66 11 88 44',
    isActive: true,
    availabilityStatus: 'OFFLINE',
    mustChangePassword: true,
    temporaryCode: '315792',
    callsTodayCount: 0,
    confirmedTodayCount: 0,
    confirmedWeekCount: 45,
    confirmedMonthCount: 190,
    cancelledTodayCount: 0,
    unreachableTodayCount: 0,
    callbacksScheduledToday: 0,
    conversionRate: 75.0,
    maxActiveOrders: 15,
    maxActiveConversations: 5,
    activeOrdersCount: 0,
    activeConversationsCount: 0,
    commissionPerConfirmation: 750,
    avgProcessingTimeMinutes: 5.5,
    languages: ['Français', 'Fon'],
    zones: ['Abomey-Calavi'],
    skills: ['Généraliste'],
    lastActivityAt: 'Hier à 18:40',
  },
];

export const initialPayoutRequests: PayoutRequest[] = [
  {
    id: 'wd-2048',
    partnerId: 'p1',
    partnerName: 'Afrimarket',
    amount: 500000,
    reservedAmount: 500000,
    operator: 'LEEKPAY',
    leekpayPhone: '+229 01 97 36 29 06',
    leekpayCountry: 'Bénin (BJ)',
    phone: '01 97 36 29 06',
    countryCode: '+229',
    requestedAt: '2026-09-04T09:30:00',
    status: 'PENDING',
    balanceBefore: 4820000,
    balanceAfter: 4320000,
    internalNote: 'Vérification bancaire effectuée. Prêt pour validation.',
  },
  {
    id: 'wd-2047',
    partnerId: 'p3',
    partnerName: 'Dossou Fashion',
    amount: 360000,
    reservedAmount: 360000,
    operator: 'USDT',
    cryptoAddress: 'TM1R9pQcKsXkQpXg8y6Jc5kZ3v4mN7bQ8L',
    cryptoNetwork: 'TRC-20 (Tron Network)',
    cryptoEstimatedUsdt: 600,
    requestedAt: '2026-09-04T08:15:00',
    status: 'IN_VERIFICATION',
    balanceBefore: 1250000,
    balanceAfter: 890000,
    internalNote: 'Contrôle adresse de wallet USDT TRC-20 en cours.',
  },
  {
    id: 'wd-2046',
    partnerId: 'p4',
    partnerName: 'Lokossa Tech Store',
    amount: 220000,
    reservedAmount: 220000,
    operator: 'BINANCE_PAY',
    binancePayId: '849201938',
    binanceEmail: 'lokossatech@gmail.com',
    requestedAt: '2026-09-03T16:45:00',
    status: 'APPROVED',
    approvedAt: '2026-09-03T17:10:00',
    adminProcessorName: 'Direction ENO (Super Admin)',
    balanceBefore: 940000,
    balanceAfter: 720000,
    internalNote: 'PayId validé via API Binance Merchant.',
  },
  {
    id: 'wd-2045',
    partnerId: 'p2',
    partnerName: 'Bénin Shop',
    amount: 120000,
    operator: 'LEEKPAY',
    leekpayPhone: '+229 01 93 83 79 06',
    phone: '01 93 83 79 06',
    countryCode: '+229',
    requestedAt: '2026-09-02T16:15:00',
    status: 'PAID',
    approvedAt: '2026-09-02T16:35:00',
    paidAt: '2026-09-02T16:40:00',
    adminProcessorName: 'Direction ENO (Super Admin)',
    paymentReference: 'LK-PAY-984214-BJ',
    txReference: 'TX-ENO-984214',
    balanceBefore: 1200000,
    balanceAfter: 1080000,
    internalNote: 'Virement LeekPay exécuté avec succès.',
  },
];

export const products: Product[] = [
  {
    id: 'prod1',
    name: 'ROULEAU DE COLORIAGE ET DESSIN MAGIQUE',
    price: 7800,
    initialStock: 150,
    remainingStock: 82,
    deliveredCount: 68,
    partnerId: 'p1',
    createdAt: '2026-01-20',
  },
  {
    id: 'prod2',
    name: 'MINI VENTILATEUR PORTATIF RECHARGEABLE USB',
    price: 9500,
    initialStock: 80,
    remainingStock: 34,
    deliveredCount: 46,
    partnerId: 'p1',
    createdAt: '2026-02-01',
  },
  {
    id: 'prod3',
    name: 'CORRECTEUR DE POSTURE DOS & ÉPAULES AJUSTABLE',
    price: 11000,
    initialStock: 60,
    remainingStock: 18,
    deliveredCount: 42,
    partnerId: 'p1',
    createdAt: '2026-02-15',
  },
  {
    id: 'prod4',
    name: 'MONTRE CONNECTÉE FITNESS PRO WATERPROOF',
    price: 18500,
    initialStock: 45,
    remainingStock: 12,
    deliveredCount: 33,
    partnerId: 'p2',
    createdAt: '2026-02-20',
  },
  {
    id: 'prod5',
    name: 'SERUM ANTI-TACHES ÉCLAT VISAGE 50ML',
    price: 14000,
    initialStock: 100,
    remainingStock: 48,
    deliveredCount: 52,
    partnerId: 'p3',
    createdAt: '2026-03-01',
  },
];

export const orders: Order[] = [
  {
    id: 'o1',
    orderNumber: 'CMD-BJ9K2L1A',
    clientName: 'SOULEYMANE DIOP',
    clientPhone: '+229 01 97 36 29 06',
    region: 'Littoral',
    address: 'AKPAKPA, Face Stade René Pleven',
    city: 'Cotonou',
    products: 'ROULEAU DE COLORIAGE (x2)',
    quantity: 2,
    totalPrice: 15600,
    deliveryFee: 2000,
    serviceFee: 800,
    status: 'EN_COURS',
    comment: 'Client confirmé par Inès. Livreur Rachad en route (créneau 14h-16h).',
    createdAt: '2026-09-03T09:15:00',
    updatedAt: '2026-09-03T11:00:00',
    partnerId: 'p1',
    partnerName: 'Afrimarket',
    assignedCloseuseId: 'cls-1',
    assignedCloseuseName: 'Inès T.',
    assignedLivreurId: 'liv-1',
    assignedLivreurName: 'Rachad A.',
    closingNotes: 'Client très réactif, prêt avec le montant exact.',
    callCount: 1,
    deliveryTimeSlot: '14h00 - 16h00',
  },
  {
    id: 'o2',
    orderNumber: 'CMD-BJH7X8P9',
    clientName: 'NADÈGE HOUNNOU',
    clientPhone: '+229 01 66 12 45 89',
    region: 'Atlantique',
    address: 'GODOMEY, Carrefour Togoudo',
    city: 'Abomey-Calavi',
    products: 'MINI VENTILATEUR RECHARGEABLE',
    quantity: 1,
    totalPrice: 9500,
    deliveryFee: 2000,
    serviceFee: 800,
    status: 'EN_ATTENTE',
    comment: 'Nouvelle commande boutique. À appeler en priorité.',
    createdAt: '2026-09-03T11:45:00',
    updatedAt: '2026-09-03T11:45:00',
    partnerId: 'p1',
    partnerName: 'Afrimarket',
    callCount: 0,
  },
  {
    id: 'o3',
    orderNumber: 'CMD-BJ3M4N5K',
    clientName: 'BRICE GBAGUIDI',
    clientPhone: '+229 01 95 88 77 44',
    region: 'Littoral',
    address: 'CADJEHOUN, Derrière Église St Michel',
    city: 'Cotonou',
    products: 'CORRECTEUR DE POSTURE',
    quantity: 1,
    totalPrice: 11000,
    deliveryFee: 2000,
    serviceFee: 800,
    status: 'CONFIRMEE',
    comment: 'Validé par Chimène. Prêt pour dispatch.',
    createdAt: '2026-09-03T08:30:00',
    updatedAt: '2026-09-03T10:15:00',
    partnerId: 'p1',
    partnerName: 'Afrimarket',
    assignedCloseuseId: 'cls-2',
    assignedCloseuseName: 'Chimène A.',
    assignedLivreurId: 'liv-1',
    assignedLivreurName: 'Rachad A.',
    closingNotes: 'Livraison bureau souhaitée avant 17h.',
    callCount: 1,
    deliveryTimeSlot: '15h30',
  },
  {
    id: 'o4',
    orderNumber: 'CMD-BJ2F4X7Y',
    clientName: 'MARIE-CLAIRE TOSSOU',
    clientPhone: '+229 01 67 89 23 45',
    region: 'Littoral',
    address: 'HAIE VIVE, Rue 12.045',
    city: 'Cotonou',
    products: 'ROULEAU DE COLORIAGE',
    quantity: 1,
    totalPrice: 7800,
    deliveryFee: 2000,
    serviceFee: 800,
    status: 'LIVREE',
    comment: 'Colis remis en main propre. Cash 7 800 F encaissé.',
    createdAt: '2026-09-02T14:00:00',
    updatedAt: '2026-09-02T16:30:00',
    deliveredAt: '2026-09-02T16:30:00',
    partnerId: 'p1',
    partnerName: 'Afrimarket',
    assignedCloseuseId: 'cls-1',
    assignedCloseuseName: 'Inès T.',
    assignedLivreurId: 'liv-1',
    assignedLivreurName: 'Rachad A.',
    codCollected: true,
  },
  {
    id: 'o5',
    orderNumber: 'CMD-BJ8R9T2W',
    clientName: 'JEAN-BAPTISTE DANSOU',
    clientPhone: '+229 01 96 44 33 22',
    region: 'Atlantique',
    address: 'TANKPÈ, Carrefour IITA',
    city: 'Abomey-Calavi',
    products: 'MINI VENTILATEUR RECHARGEABLE',
    quantity: 2,
    totalPrice: 19000,
    deliveryFee: 2000,
    serviceFee: 800,
    status: 'A_RAPPELER',
    comment: 'Injoignable 1er appel (occupé). Rappel programmé à 17h00.',
    createdAt: '2026-09-03T10:00:00',
    updatedAt: '2026-09-03T11:20:00',
    partnerId: 'p1',
    partnerName: 'Afrimarket',
    assignedCloseuseId: 'cls-1',
    assignedCloseuseName: 'Inès T.',
    closingNotes: 'Téléphone sonne mais ne décroche pas.',
    callCount: 1,
  },
  {
    id: 'o6',
    orderNumber: 'CMD-BJ5K9L2M',
    clientName: 'AÏCHA CISSE',
    clientPhone: '+229 01 68 00 11 22',
    region: 'Ouémé',
    address: 'OUANDO, Marché Ouando',
    city: 'Porto-Novo',
    products: 'SÉRUM ANTI-TACHES ÉCLAT',
    quantity: 1,
    totalPrice: 14000,
    deliveryFee: 2000,
    serviceFee: 800,
    status: 'EN_COURS',
    comment: 'Confirmé. Livreur Rodrigue en route.',
    createdAt: '2026-09-03T09:40:00',
    updatedAt: '2026-09-03T11:10:00',
    partnerId: 'p3',
    partnerName: 'Dossou Fashion (CI)',
    assignedCloseuseId: 'cls-2',
    assignedCloseuseName: 'Chimène A.',
    assignedLivreurId: 'liv-3',
    assignedLivreurName: 'Rodrigue K.',
    deliveryTimeSlot: '15h00',
  },
];

export function getPartnerById(partnerId: string): Partner | undefined {
  return partners.find((p) => p.id === partnerId);
}

export function getPartnerOrders(partnerId: string): Order[] {
  return orders.filter((o) => o.partnerId === partnerId);
}

export function getPartnerProducts(partnerId: string): Product[] {
  return products.filter((p) => p.partnerId === partnerId);
}

export function formatCFA(amount: number): string {
  return new Intl.NumberFormat('fr-FR').format(amount) + ' FCFA';
}

export function formatPrice(amount: number): string {
  return new Intl.NumberFormat('fr-FR').format(amount) + ' FCFA';
}

export function generateOrderNumber(): string {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  let result = 'CMD-BJ';
  for (let i = 0; i < 6; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return result;
}

// 🟢 Activité temps réel de l'agence (Agency Pulse)
export const initialAgencyPulseActivities: ActivityItem[] = [
  {
    id: 'act-1',
    type: 'ORDER_DELIVERED',
    title: 'Livraison réussie & COD encaissé',
    description: 'Rodrigue K. a remis le colis CMD-BJ5K9L2M (14 000 F) à Ouando.',
    time: 'Il y a 3 min',
    orderNumber: 'CMD-BJ5K9L2M',
    partnerName: 'Dossou Fashion',
    amount: 14000,
  },
  {
    id: 'act-2',
    type: 'ORDER_CONFIRMED',
    title: 'Commande confirmée par Closing',
    description: 'Inès T. a validé la commande CMD-BJ7X8Y9Z après 1 appel (15 min).',
    time: 'Il y a 11 min',
    orderNumber: 'CMD-BJ7X8Y9Z',
    partnerName: 'Afrimarket',
    amount: 23400,
  },
  {
    id: 'act-3',
    type: 'ORDER_DISPATCHED',
    title: 'Colis assigné au livreur de zone',
    description: 'CMD-BJ3C4D5E assignée à Gaston B. (Zone Akpakpa & PK10).',
    time: 'Il y a 18 min',
    orderNumber: 'CMD-BJ3C4D5E',
    partnerName: 'Bénin Shop',
    amount: 15600,
  },
  {
    id: 'act-4',
    type: 'PAYOUT_REQUESTED',
    title: 'Nouvelle demande de retrait soumise',
    description: 'Dossou Fashion demande 360 000 F CFA en USDT TRC-20.',
    time: 'Il y a 32 min',
    partnerName: 'Dossou Fashion',
    amount: 360000,
  },
  {
    id: 'act-5',
    type: 'MESSAGE_RECEIVED',
    title: 'Message urgent reçu au Support',
    description: 'Afrimarket : "Pouvez-vous prioriser la livraison à Haie Vive ?"',
    time: 'Il y a 45 min',
    partnerName: 'Afrimarket',
  },
];

// 💬 Conversations du Hub de Communication
export const initialConversations: Conversation[] = [
  {
    id: 'conv-1',
    partnerId: 'p1',
    partnerName: 'Jude Sina',
    companyName: 'Afrimarket',
    phone: '+229 01 97 36 29 06',
    lastMessage: 'Bonjour ! Quel est le délai moyen pour le virement MTN Money demandé ce matin ?',
    lastMessageAt: '11:42',
    unreadCount: 2,
    status: 'URGENT',
    priority: 'HIGH',
    assignedAgentName: 'Inès TOVIHOUDJI',
    assignedAgentRole: 'Superviseure Support',
    relatedOrderNumber: 'CMD-BJ7X8Y9Z',
    messages: [
      {
        id: 'm1',
        sender: 'PARTNER',
        senderName: 'Jude Sina (Afrimarket)',
        text: 'Bonjour le support ENO ! J\'ai 3 nouvelles commandes enregistrées sur Cotonou.',
        sentAt: '11:20',
      },
      {
        id: 'm2',
        sender: 'BOT',
        senderName: 'Assistant ENO',
        text: 'Bonjour Afrimarket ! Vos commandes ont été transmises à notre pôle closing. Nos opératrices appellent les clients sous 15 min.',
        sentAt: '11:21',
      },
      {
        id: 'm3',
        sender: 'PARTNER',
        senderName: 'Jude Sina (Afrimarket)',
        text: 'Parfait. Quel est le délai moyen pour le virement MTN Money demandé ce matin ?',
        sentAt: '11:42',
      },
    ],
  },
  {
    id: 'conv-2',
    partnerId: 'p3',
    partnerName: 'Marie Dossou',
    companyName: 'Dossou Fashion (Côte d\'Ivoire)',
    phone: '+225 07 45 12 30 89',
    lastMessage: 'J\'ai bien renseigné mon adresse USDT TRC-20 pour le reversement des fonds.',
    lastMessageAt: '10:15',
    unreadCount: 0,
    status: 'WAITING',
    priority: 'MEDIUM',
    assignedAgentName: 'Jude (PDG)',
    assignedAgentRole: 'Direction Générale',
    messages: [
      {
        id: 'm21',
        sender: 'PARTNER',
        senderName: 'Marie Dossou',
        text: 'Bonjour Monsieur, mes fonds de ventes à Cotonou sont prêts à être retirés en USDT.',
        sentAt: '10:10',
      },
      {
        id: 'm22',
        sender: 'PARTNER',
        senderName: 'Marie Dossou',
        text: 'J\'ai bien renseigné mon adresse USDT TRC-20 pour le reversement des fonds.',
        sentAt: '10:15',
      },
    ],
  },
  {
    id: 'conv-3',
    partnerId: 'p2',
    partnerName: 'Marius Houngbo',
    companyName: 'Bénin Shop Électro',
    phone: '+229 01 93 83 79 06',
    lastMessage: 'Merci pour la confirmation rapide du client de Calavi ! Super closing.',
    lastMessageAt: 'Hier',
    unreadCount: 0,
    status: 'RESOLVED',
    priority: 'LOW',
    assignedAgentName: 'Chimène A.',
    assignedAgentRole: 'Closeuse Senior',
    messages: [
      {
        id: 'm31',
        sender: 'PARTNER',
        senderName: 'Marius Houngbo',
        text: 'Merci pour la confirmation rapide du client de Calavi ! Super closing.',
        sentAt: 'Hier 16:30',
      },
    ],
  },
];

// ⚠️ Alertes Intelligentes du Centre d'Attention
export const initialAgencyAlerts: AgencyAlert[] = [
  {
    id: 'alt-1',
    severity: 'CRITICAL',
    title: '3 demandes de retrait nécessitent votre arbitrage',
    description: 'Montant cumulé : 612 400 F CFA en attente de déblocage (MTN Money & USDT TRC-20).',
    actionLabel: 'Arbitrer les retraits',
    actionHref: '/admin/finances',
    count: 3,
  },
  {
    id: 'alt-2',
    severity: 'WARNING',
    title: '1 client à rappeler en urgence',
    description: 'CMD-BJ9G0H1I (Afrimarket) — Injoignable au 1er appel, rappel programmé cet après-midi.',
    actionLabel: 'Voir la file closing',
    actionHref: '/admin/commandes',
    count: 1,
  },
  {
    id: 'alt-3',
    severity: 'INFO',
    title: 'Stock bas détecté : 1 produit sous le seuil critique',
    description: 'Pack Savon Noir & Curcuma (Bénin Shop) — Moins de 10 unités en entrepôt Cotonou.',
    actionLabel: 'Planifier ramassage',
    actionHref: '/admin/stocks',
    count: 1,
  },
];

// 💰 Grand Livre de Trésorerie (Journal Financier d'ENO)
export const initialTransactions: FinancialTransaction[] = [
  {
    id: 'tx-10482',
    txReference: 'TX-2026-0903-084',
    date: '2026-09-03 18:35',
    type: 'ENCAISSEMENT_COD',
    label: 'Encaissement COD Commande CMD-1041',
    partnerId: 'p1',
    partnerName: 'Afrimarket',
    livreurId: 'liv-1',
    livreurName: 'Rachad ADECHINA',
    orderNumber: 'CMD-1041',
    inflow: 38000,
    outflow: 0,
    balanceAfter: 14850000,
    status: 'COMPLETED',
    notes: 'Espèces encaissées par Rachad et transmises au Hub Cadjehoun.',
  },
  {
    id: 'tx-10481',
    txReference: 'TX-2026-0903-083',
    date: '2026-09-03 18:36',
    type: 'COMMISSION_ENO',
    label: 'Commission ENO (Livraison 2 000 + Closing 800)',
    partnerId: 'p1',
    partnerName: 'Afrimarket',
    orderNumber: 'CMD-1041',
    inflow: 2800,
    outflow: 0,
    balanceAfter: 14850000,
    status: 'COMPLETED',
    notes: 'Revenu net agence prélevé automatiquement.',
  },
  {
    id: 'tx-10480',
    txReference: 'TX-2026-0903-082',
    date: '2026-09-03 18:36',
    type: 'CREDIT_MARCHAND',
    label: 'Crédit Solde Afrimarket (Net marchand 35 200 FCFA)',
    partnerId: 'p1',
    partnerName: 'Afrimarket',
    orderNumber: 'CMD-1041',
    inflow: 0,
    outflow: 35200,
    balanceAfter: 14814800,
    status: 'COMPLETED',
    notes: 'Solde e-commerçant crédité et disponible pour retrait.',
  },
  {
    id: 'tx-10479',
    txReference: 'TX-2026-0903-079',
    date: '2026-09-03 16:40',
    type: 'RETRAIT',
    label: 'Retrait Marchand Bénin Shop (MTN Mobile Money)',
    partnerId: 'p2',
    partnerName: 'Bénin Shop',
    inflow: 0,
    outflow: 120000,
    balanceAfter: 14812000,
    status: 'COMPLETED',
    notes: 'Virement validé par la Direction. Réf: MTN-TX-984214.',
  },
  {
    id: 'tx-10478',
    txReference: 'TX-2026-0903-075',
    date: '2026-09-03 14:15',
    type: 'DEPENSE',
    label: 'Carburant Flotte Coursiers Hub Cotonou',
    inflow: 0,
    outflow: 45000,
    balanceAfter: 14932000,
    status: 'COMPLETED',
    notes: 'Avance carburant 9 motos de tournée.',
  },
  {
    id: 'tx-10477',
    txReference: 'TX-2026-0903-068',
    date: '2026-09-03 11:30',
    type: 'ENCAISSEMENT_COD',
    label: 'Encaissement COD Commande CMD-1035',
    partnerId: 'p3',
    partnerName: 'Dossou Fashion',
    livreurId: 'liv-2',
    livreurName: 'Wilfried HOUNGBO',
    orderNumber: 'CMD-1035',
    inflow: 65000,
    outflow: 0,
    balanceAfter: 14977000,
    status: 'COMPLETED',
    notes: 'Espèces encaissées à Fidjrossè.',
  },
];

// 💵 Encaissements COD individuels par commande livrée
export const initialCodCollections: CodCollection[] = [
  {
    orderId: 'cmd_001',
    orderNumber: 'CMD-1048',
    partnerId: 'p1',
    partnerName: 'Afrimarket',
    clientName: 'Marcelle AGUESSY',
    clientPhone: '+229 01 97 45 12 00',
    livreurId: 'liv-1',
    livreurName: 'Rachad ADECHINA',
    expectedAmount: 38000,
    collectedAmount: 38000,
    discrepancy: 0,
    collectionStatus: 'COLLECTED',
    remittanceStatus: 'HELD_BY_DRIVER',
    deliveredAt: '2026-09-04 10:15',
  },
  {
    orderId: 'cmd_002',
    orderNumber: 'CMD-1047',
    partnerId: 'p2',
    partnerName: 'Bénin Shop',
    clientName: 'Gérard HOUNSOU',
    clientPhone: '+229 01 66 33 22 11',
    livreurId: 'liv-2',
    livreurName: 'Wilfried HOUNGBO',
    expectedAmount: 25000,
    collectedAmount: 20000,
    discrepancy: -5000,
    discrepancyJustification: 'Client a retiré un flacon cosmétique après accord téléphonique du marchand.',
    collectionStatus: 'DISCREPANCY_FLAGGED',
    remittanceStatus: 'DISCREPANCY_DETECTED',
    deliveredAt: '2026-09-04 09:40',
  },
  {
    orderId: 'cmd_003',
    orderNumber: 'CMD-1046',
    partnerId: 'p3',
    partnerName: 'Dossou Fashion',
    clientName: 'Nadège KIKI',
    clientPhone: '+229 01 95 11 22 33',
    livreurId: 'liv-1',
    livreurName: 'Rachad ADECHINA',
    expectedAmount: 42000,
    collectedAmount: 42000,
    discrepancy: 0,
    collectionStatus: 'COLLECTED',
    remittanceStatus: 'HELD_BY_DRIVER',
    deliveredAt: '2026-09-04 09:20',
  },
  {
    orderId: 'cmd_004',
    orderNumber: 'CMD-1045',
    partnerId: 'p4',
    partnerName: 'Lokossa Tech Store',
    clientName: 'Ablam AMEGAN',
    clientPhone: '+229 01 62 88 99 00',
    livreurId: 'liv-3',
    livreurName: 'Boris TCHICAYA',
    expectedAmount: 75000,
    collectedAmount: 75000,
    discrepancy: 0,
    collectionStatus: 'COLLECTED',
    remittanceStatus: 'REMITTED',
    deliveredAt: '2026-09-03 17:30',
    remittanceId: 'rem-102',
  },
  {
    orderId: 'cmd_005',
    orderNumber: 'CMD-1044',
    partnerId: 'p1',
    partnerName: 'Afrimarket',
    clientName: 'Diane SOSSOU',
    clientPhone: '+229 01 93 11 00 22',
    livreurId: 'liv-3',
    livreurName: 'Boris TCHICAYA',
    expectedAmount: 18500,
    collectedAmount: 18500,
    discrepancy: 0,
    collectionStatus: 'COLLECTED',
    remittanceStatus: 'VALIDATED',
    deliveredAt: '2026-09-03 16:10',
    remittanceId: 'rem-101',
  },
];

// 🏦 Remises de Fonds des Livreurs (Dépôt d'espèces à l'agence)
export const initialCodRemittances: CodRemittance[] = [
  {
    id: 'rem-103',
    reference: 'REM-2026-0904-003',
    livreurId: 'liv-1',
    livreurName: 'Rachad ADECHINA',
    amountExpected: 80000,
    amountDeclared: 80000,
    ordersCount: 2,
    orderIds: ['cmd_001', 'cmd_003'],
    period: 'Matinée du 04 Septembre 2026',
    createdAt: '2026-09-04 10:45',
    status: 'PENDING_VALIDATION',
    notes: 'Remise en espèces déposée à la caisse Hub Cadjehoun.',
  },
  {
    id: 'rem-102',
    reference: 'REM-2026-0903-002',
    livreurId: 'liv-3',
    livreurName: 'Boris TCHICAYA',
    amountExpected: 250000,
    amountDeclared: 250000,
    amountValidated: 250000,
    discrepancyAmount: 0,
    ordersCount: 8,
    orderIds: ['cmd_004', 'cmd_005'],
    period: 'Tournée Après-midi 03 Septembre',
    createdAt: '2026-09-03 18:30',
    validatedAt: '2026-09-03 18:45',
    validatedBy: 'Direction ENO (Super Admin)',
    status: 'VALIDATED',
    notes: 'Comptage physique effectué et validé au coffre-fort.',
  },
  {
    id: 'rem-101',
    reference: 'REM-2026-0902-001',
    livreurId: 'liv-2',
    livreurName: 'Wilfried HOUNGBO',
    amountExpected: 300000,
    amountDeclared: 295000,
    amountValidated: 295000,
    discrepancyAmount: -5000,
    discrepancyJustification: 'Écart de 5 000 FCFA sur commande CMD-1047 justifié par le marchand.',
    ordersCount: 11,
    orderIds: ['cmd_002'],
    period: 'Journée du 02 Septembre 2026',
    createdAt: '2026-09-02 19:10',
    validatedAt: '2026-09-02 19:30',
    validatedBy: 'Direction ENO (Super Admin)',
    status: 'PARTIALLY_VALIDATED',
    notes: 'Écart accepté après vérification avec le commerçant Bénin Shop.',
  },
];

// 📜 Journal d'Audit Financier Non-Destructif
export const initialFinancialAuditLogs: FinancialAuditLog[] = [
  {
    id: 'aud-1',
    timestamp: '2026-09-04 10:45',
    action: 'Remise de fonds déclarée',
    actor: 'Rachad ADECHINA (Livreur)',
    targetType: 'REMITTANCE',
    targetId: 'REM-2026-0904-003',
    amount: 80000,
    details: 'Déclaration de remise d\'espèces de 80 000 FCFA sur 2 commandes.',
  },
  {
    id: 'aud-2',
    timestamp: '2026-09-04 09:40',
    action: 'Écart d\'encaissement signalé',
    actor: 'Wilfried HOUNGBO (Livreur)',
    targetType: 'DISCREPANCY',
    targetId: 'CMD-1047',
    amount: -5000,
    details: 'Montant attendu: 25 000 FCFA, collecté: 20 000 FCFA. Justification: modification marchand.',
  },
  {
    id: 'aud-3',
    timestamp: '2026-09-04 09:30',
    action: 'Demande de retrait créée & solde réservé',
    actor: 'Afrimarket (E-commerçant)',
    targetType: 'WITHDRAWAL',
    targetId: 'WD-2048',
    amount: 500000,
    details: 'Demande LeekPay de 500 000 FCFA. 500 000 FCFA déplacés en montant réservé.',
  },
  {
    id: 'aud-4',
    timestamp: '2026-09-03 18:45',
    action: 'Remise de fonds validée',
    actor: 'Direction ENO (Super Admin)',
    targetType: 'REMITTANCE',
    targetId: 'REM-2026-0903-002',
    amount: 250000,
    details: 'Validation intégrale sans écart de 250 000 FCFA (Boris TCHICAYA).',
  },
  {
    id: 'aud-5',
    timestamp: '2026-09-02 16:40',
    action: 'Virement de retrait exécuté & archivé',
    actor: 'Direction ENO (Super Admin)',
    targetType: 'WITHDRAWAL',
    targetId: 'WD-2045',
    amount: 120000,
    details: 'Règlement LeekPay validé. Réf: LK-PAY-984214-BJ.',
  },
];

